services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongodb
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URI=mongodb://mongo:27017/db_3clean
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
