services:
  app:
    build: .
    container_name: express-app
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongodb
    environment:
      - PORT=3000
      - NODE_ENV=development
      - JWT_SECRET=pssthereisursecretkey
      - MONGODB_URL=mongodb://mongodb:27017/db_3clean
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/usr/src/app
    networks:
      - backend

  redis:
    image: redis:alpine
    platform: linux/amd64
    container_name: redis
    command: [ "redis-server", "--maxmemory", "128mb", "--maxmemory-policy", "volatile-lru", "--save", "" ]
    ports:
      - "6379:6379"
    networks:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge
